### ISSUE TITLE
Automaticly crop sketch

### ISSUE THREAD

**Issue by GeleArthur** [ClipplerBlood/sketch-tiles#1]
I would like it if the sketch would automaticly form to the size as big as the drawing.
Right now the only way to "crop" is to scale the window.

**Comment by ClipplerBlood** [comment]
Feature added 🚀 

I'd appreciate if you could test the pre-release here 
[https://github.com/ClipplerBlood/sketch-tiles/releases/download/1.0.1/module.json](https://github.com/ClipplerBlood/sketch-tiles/releases/download/1.0.1/module.json)
Let me know if it works properly or if there are any bugs
Ty for the suggestion!

PS: It is a setting in the "other" tab (off by default)

**Comment by GeleArthur** [comment]
That was quick. Its working like an charm.
Thanks 😃
