### ISSUE TITLE
New drawing as a hidden tile

### ISSUE THREAD

**Issue by Cacuu** [ClipplerBlood/sketch-tiles#4]
When Playing the game I would like to sometimes draw something a little ahead of time and send it. For now I keep multiple sketch tiles open until it's time to upload, but it would be nice to upload and position them, and then revealing when the time is right

**Comment by ClipplerBlood** [comment]
Great feature!
Implemented it in version 1.0.2 🚀 

Let me know if it works properly or if you find any bugs. Cheers!
