### ISSUE TITLE
Foundry 11 support

### ISSUE THREAD

**Issue by dmpunks** [ClipplerBlood/sketch-tiles#7]
The drawing window to draw upon no longer pops up when the Index Card icon is clicked. In the console, there is only the screenshot below. No other errors or details appear:
![image](https://github.com/ClipplerBlood/sketch-tiles/assets/1963509/d6409009-b691-44fd-a68e-2fdb7384b95c)

**Comment by ClipplerBlood** [comment]
Should be fixed in 1.0.3 😄
